blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/NoahNxT/Toggl2Timeshit/security/policy
    about: Please report security issues via the security policy.
